name: "Samply.Lens verify new Release"
on:
  pull_request:
    branches:
      - main

jobs:
  verify-new-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git checkout --track origin/${{ github.event.repository.default_branch }}
      - run: git checkout ${{ github.head_ref }}
      - name: "Ensure Package Version changed"
        run: |
            if [ "$(git diff ${{ github.event.repository.default_branch }} ${{ github.head_ref }} -- package.json | grep version | wc -l)" -eq 0 ]; then \
              echo "::error:: Please update the version of package.json according to the semantic versioning guidelines!"; \
              exit 1; \
            fi
      - name: "Ensure Package Version for core changed"
        run: |
            if [ "$(git diff ${{ github.event.repository.default_branch }} ${{ github.head_ref }} -- core/package.json | grep version | wc -l)" -eq 0 ]; then \
              echo "::error:: Please update the version of core/package.json according to the semantic versioning guidelines!"; \
              exit 1; \
            fi
      - name: "Ensure Package Version for components changed"
        run: |
            if [ "$(git diff ${{ github.event.repository.default_branch }} ${{ github.head_ref }} -- components/package.json | grep version | wc -l)" -eq 0 ]; then \
              echo "::error:: Please update the version of components/package.json according to the semantic versioning guidelines!"; \
              exit 1; \
            fi
      - name: "Ensure Package Version for auth changed"
        run: |
            if [ "$(git diff ${{ github.event.repository.default_branch }} ${{ github.head_ref }} -- auth/package.json | grep version | wc -l)" -eq 0 ]; then \
              echo "::error:: Please update the version of auth/package.json according to the semantic versioning guidelines!"; \
              exit 1; \
            fi
